Transform: AWS::Serverless-2016-10-31
Parameters:
  HostName:
    Type: String
  DomainName:
    Type: String
  SSLCertificateArn:
    Type: String
  AuthString:
    Type: String
Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
  ContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - Fn::Sub: ${ContentBucket.Arn}/*
          Principal:
            Service: cloudfront.amazonaws.com
          Condition:
            StringEquals:
              AWS:SourceArn:
                Fn::Sub: arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}
  OriginAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${ContentBucket}-Access
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  WebACL:
    Type: AWS::WAFv2::WebACL
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: CreatedByCloudFront-f4b25d32
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: CreatedByCloudFront-f4b25d32
      Rules:
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 0
          OverrideAction:
            Count: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesAmazonIpReputationList
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            Count: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSet
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            Count: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesKnownBadInputsRuleSet
  CloudFrontAuthFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: KBK-History-Auth
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          const request = event.request;
          const headers = request.headers;
          const authString = "${AuthString}";
          const basicAuthHeader = headers.authorization && headers.authorization.value && headers.authorization.value.split(' ')[1];

          // Check for the presence of the Authorization header with the correct password
          if (basicAuthHeader) {
            const authParts = atob(basicAuthHeader).split(':');
            const password = authParts[1];
            if (password === authString) {
              return request;
            }
          }

          // If the header is missing or incorrect, return a 401 Unauthorized response
          return {
            statusCode: 401,
            statusDescription: 'Unauthorized',
            headers: {
              'www-authenticate': { value: 'Basic realm="KBK Users (Contact Michael for the password)"' }
            }
          }
        }
      FunctionConfig:
        Comment: "Authentication function for KBK History site"
        Runtime: cloudfront-js-2.0
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        WebACLId: !GetAtt WebACL.Arn
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificateArn
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        Enabled: true
        Aliases:
        - !Sub ${HostName}.${DomainName}
        Origins:
        - Id: S3Origin
          DomainName: !Sub "${ContentBucket.DomainName}"
          S3OriginConfig:
            OriginAccessIdentity: ''
          OriginAccessControlId: !Sub "${OriginAccess.Id}"
        CacheBehaviors:
          - PathPattern: /assets/*
            TargetOriginId: S3Origin
            AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            CachedMethods:
            - GET
            - HEAD
            - OPTIONS
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
            ViewerProtocolPolicy: redirect-to-https
            FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Ref CloudFrontAuthFunction
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          CachedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
          - EventType: viewer-request
            FunctionARN: !Ref CloudFrontAuthFunction
        DefaultRootObject: index.html
Outputs:
  ContentBucketName:
    Value:
      Ref: ContentBucket
  CloudFrontDomainName:
    Value:
      Fn::GetAtt:
      - CloudFrontDistribution
      - DomainName
  WebACLArn:
    Value: !GetAtt WebACL.Arn